include Utilities so that make works
Else the following error happens:
g++ -g -std=c++20 -Wall -Wextra -Wsuggest-override -Wnon-virtual-dtor -I. -I./include -I/home/alfredo/Documents/Polimi/PACS/pacs-examples/Examples/include  -I/u/sw/toolchains/gcc-glibc/11.2.0/pkgs/eigen/3.3.9/include/eigen3      -c -o main_rational.o main_rational.cpp
In file included from main_rational.cpp:1:
rational.hpp:6:10: fatal error: hashCombine.hpp: No such file or directory
    6 | #include "hashCombine.hpp" // for the hash function
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: main_rational.o] Error 1